services:
  questlog_mvc:
    image: ${DOCKER_REGISTRY-}questlogmvc
    build:
      context: .
      dockerfile: QuestLog/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: "Production"
    ports:
      - 5002:8080
      - 5003:443

  quests:
    image: ${DOCKER_REGISTRY-}quests
    build:
      context: .
      dockerfile: QuestLog_Quests/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: "Production"
    ports:
      - 5004:8080
      - 5005:443
    networks:
      - default

  questlog_db:
    image: mysql:latest
    volumes:
      - database:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: 4ojj3xyd
      MYSQL_CHARSET: utf8mb4
      MYSQL_COLLATION: utf8mb4_swedish_ci
      MYSQL_PORT: 3306
    ports:
      - 5001:3306
    networks:
      - default
    restart:
      always
    
volumes:
  database:
    driver: local
